### ISSUE TITLE
game-server image no longer building

### ISSUE THREAD

**Issue by jamesla** [jkuettner/bfbc2-server#7]
Looks like the game-server is no longer building due to it failing to download directx redistributables.

Any idea what's causing that?

**Comment by jkuettner** [comment]
Hey, thanks for the heads-up. I had actually planned to update the parent images a while ago, since Ubuntu Bionic is EOL.

Could you please try out [this branch](https://github.com/jkuettner/bfbc2-server/tree/gameserver-to-bookworm) here? I only know that the images build on my end, but I haven't had time to check the functionality yet.

**Comment by jkuettner** [comment]
I managed to find some time today after all. I didn't try the old version again, but with the new version [v1.1.0](https://github.com/jkuettner/bfbc2-server/releases/tag/v1.1.0), I was able to run a server and play on it.

Therefore, I’m closing the issue, but feel free to reopen it if any other problems occur.
